version: "3.8"

services:

  master:
    build:
      context: ./locust
      dockerfile: Dockerfile
    ports: [ "8089:8089" ]
    env_file: [ "./.env" ]
    command: --conf /mnt/locust/.master.conf

  worker-1:
    build:
      context: ./locust
      dockerfile: Dockerfile
    env_file: [ "./.env" ]
    command: --conf /mnt/locust/.worker.conf

  worker-2:
    build:
      context: ./locust
      dockerfile: Dockerfile
    env_file: [ "./.env" ]
    command: --conf /mnt/locust/.worker.conf

  worker-3:
    build:
      context: ./locust
      dockerfile: Dockerfile
    env_file: [ "./.env" ]
    command: --conf /mnt/locust/.worker.conf
