version: "3.8"

services:

  dummy:
    build:
      context: ./
      dockerfile: Dockerfile
    ports: [ "8080:8080" ]

  locust:
    build:
      context: ./locust
      dockerfile: Dockerfile
    ports: [ "8089:8089" ]
    depends_on: [ "dummy" ]
